"""align user_id uuid and payment enums

Revision ID: 107e66e8ace8
Revises: c49aa8ab3a6b
Create Date: 2026-07-23 14:14:43.039297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107e66e8ace8'
down_revision: Union[str, Sequence[str], None] = 'c49aa8ab3a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
